const APP_KEY='woodsy-cinematheque-v3';
const LIB_KEY='woodsy-cinematheque-library-v3';
const DEFAULT_STATE={selectedMonth:'2026-10',completed:{},notes:{},monthNotes:{},added:{}};
const seedLibrary=[
  {id:'book-convenience-store-woman',title:'편의점 인간',originalTitle:'コンビニ人間',type:'book',year:2016,creator:'무라타 사야카',rating:null,historicalStatus:'read',source:'manual',sourceUrl:'',tags:['existing-read']},
  {id:'book-face-of-another',title:'타인의 얼굴',originalTitle:'他人の顔',type:'book',year:1964,creator:'아베 고보',rating:null,historicalStatus:'read',source:'manual',sourceUrl:'',tags:['existing-read']}
];
const months={
'2026-10':{label:'OCTOBER 2026',title:'WHEN A FILM CHANGES ITS MIND',ko:'현실이 어느 순간 다른 감각으로 열리는 영화들',note:'익숙한 현실이 기억, 욕망, 상실, 정체성에 의해 다른 감각으로 열리는 순간을 따라간다. 장르와 시간, 공간의 규칙이 서서히 변하는 영화들을 한 달의 경로로 묶는다.',concepts:['ABSENCE','DOUBLENESS','REPETITION','UNSTABLE PERCEPTION','BODY / PERFORMANCE','GHOSTLINESS'],core:['hiroshima','asako','personal-shopper','atlantics','holy-motors','perfect-days','the-master','ending-things'],supp:['first-love','duras-hiroshima','ripley','maiko']},
'2026-11':{label:'NOVEMBER 2026',title:'THE LIFE I COULD HAVE LIVED',ko:'내가 살 수도 있었던 삶',note:'현재의 삶 옆에 다른 이름으로 살았을 삶, 다른 사람과 함께했을 삶, 떠나지 않았다면 이어졌을 삶, 부모가 되었거나 되지 않았을 삶이 희미하게 남아 있다. 11월에는 선택하지 않은 삶이 현재에 어떤 흔적으로 남는가를 본다.',concepts:['UNLIVED LIFE','PASSING','CHOICE','MEMORY','FAMILY POSSIBILITY'],core:['passing','priscilla','return-seoul','45-years','lost-daughter','private-life','things-to-come','columbus'],supp:['unorthodox','one-day','pachinko','lessons-chemistry','book-passing','territory-light','lowland','years']},
'2026-12':{label:'DECEMBER 2026',title:'THE HOUSE REMEMBERS',ko:'집은 기억한다',note:'생활하는 집에서 시작해 흔들리는 집, 떠난 사람이 남은 집, 기억이 불안정해진 집, 시간을 품은 집으로 이동한다. 감정이 설명되지 않고 공간과 소리, 반복되는 행위 속에 저장되는 영화들을 본다.',concepts:['HOME','PLACE MEMORY','REPETITION','LOSS','SOUND / SPACE'],core:['taste-things','a-separation','after-love','the-father','petite-maman','paterson','ghost-story','memoria'],supp:['hill-house','maid','archive81','housekeeping','austerlitz','memory-police','poetics-space']},
'2027-01':{label:'JANUARY 2027',title:'PERFORMING A SELF',ko:'나라는 역할을 연기하기',note:'직업, 외모, 성별, 욕망, 사회가 요구하는 정상성. 사람이 자기 자신이라고 믿는 것이 얼마나 많은 연기와 반복으로 만들어지는지를 신체와 퍼포먼스를 통해 본다.',concepts:['PERFORMANCE','MASK','DISCIPLINE','GAZE','TRANSFORMATION'],core:['wrestler','neon-demon','black-swan','piano-teacher','shame','different-man','saint-maud','titane'],supp:['severance','ripley','mask-girl','goffman','argonauts','piano-player-book','confessions-mask','book-convenience-store-woman','book-face-of-another']}
};
const W=(id,title,originalTitle,type,creator,year,role='CORE',tags=[])=>({id,title,originalTitle,type,creator,year,role,tags});
const works=[
W('hiroshima','히로시마 내 사랑','Hiroshima mon amour','film','Alain Resnais',1959),W('asako','아사코','寝ても覚めても','film','Ryusuke Hamaguchi',2018),W('personal-shopper','퍼스널 쇼퍼','Personal Shopper','film','Olivier Assayas',2016),W('atlantics','애틀랜틱스','Atlantique','film','Mati Diop',2019),W('holy-motors','홀리 모터스','Holy Motors','film','Leos Carax',2012),W('perfect-days','퍼펙트 데이즈','Perfect Days','film','Wim Wenders',2023),W('the-master','마스터','The Master','film','Paul Thomas Anderson',2012),W('ending-things','이제 그만 끝낼까 해',"I'm Thinking of Ending Things",'film','Charlie Kaufman',2020),
W('first-love','퍼스트 러브 하츠코이','First Love','series','Kanchiku Yuri',2022,'EXPLORE'),W('duras-hiroshima','히로시마 내 사랑','Hiroshima mon amour','book','Marguerite Duras',1960,'READING'),W('ripley','리플리: 더 시리즈','Ripley','series','Steven Zaillian',2024,'EXPLORE'),W('maiko','마이코네 행복한 밥상','The Makanai','series','Hirokazu Kore-eda',2023,'EXPLORE'),
W('passing','패싱','Passing','film','Rebecca Hall',2021),W('priscilla','프리실라','Priscilla','film','Sofia Coppola',2023),W('return-seoul','리턴 투 서울','Return to Seoul','film','Davy Chou',2022),W('45-years','45년 후','45 Years','film','Andrew Haigh',2015),W('lost-daughter','로스트 도터','The Lost Daughter','film','Maggie Gyllenhaal',2021),W('private-life','프라이빗 라이프','Private Life','film','Tamara Jenkins',2018),W('things-to-come','다가오는 것들','Things to Come','film','Mia Hansen-Løve',2016),W('columbus','콜럼버스','Columbus','film','Kogonada',2017),
W('unorthodox','그리고 베를린에서','Unorthodox','series','Anna Winger / Alexa Karolinski',2020,'LONG FORM'),W('one-day','원 데이','One Day','series','Nicole Taylor',2024,'LONG FORM'),W('pachinko','파친코','Pachinko','series','Soo Hugh',2022,'EXPLORE'),W('lessons-chemistry','레슨 인 케미스트리','Lessons in Chemistry','series','Lee Eisenberg',2023,'EXPLORE'),W('book-passing','패싱','Passing','book','Nella Larsen',1929,'READING'),W('territory-light','빛의 영역','Territory of Light','book','쓰시마 유코',1979,'READING'),W('lowland','저지대','The Lowland','book','Jhumpa Lahiri',2013,'READING'),W('years','세월','Les Années','book','Annie Ernaux',2008,'READING'),
W('taste-things','프렌치 수프','The Taste of Things','film','Trần Anh Hùng',2023),W('a-separation','씨민과 나데르의 별거','A Separation','film','Asghar Farhadi',2011),W('after-love','사랑 후의 두 여자','After Love','film','Aleem Khan',2020),W('the-father','더 파더','The Father','film','Florian Zeller',2020),W('petite-maman','쁘띠 마망','Petite Maman','film','Céline Sciamma',2021),W('paterson','패터슨','Paterson','film','Jim Jarmusch',2016),W('ghost-story','고스트 스토리','A Ghost Story','film','David Lowery',2017),W('memoria','메모리아','Memoria','film','Apichatpong Weerasethakul',2021),
W('hill-house','힐 하우스의 유령','The Haunting of Hill House','series','Mike Flanagan',2018,'LONG FORM'),W('maid','조용한 희망','Maid','series','Molly Smith Metzler',2021,'EXPLORE'),W('archive81','아카이브 81','Archive 81','series','Rebecca Sonnenshine',2022,'EXPLORE'),W('housekeeping','하우스키핑','Housekeeping','book','Marilynne Robinson',1980,'READING'),W('austerlitz','아우스터리츠','Austerlitz','book','W. G. Sebald',2001,'READING'),W('memory-police','은밀핔 결정','The Memory Police','book','Yoko Ogawa',1994,'READING'),W('poetics-space','공간의 시학','La Poétique de l’espace','book','Gaston Bachelard',1958,'READING'),
W('wrestler','더 레슬러','The Wrestler','film','Darren Aronofsky',2008),W('neon-demon','네온 데몬','The Neon Demon','film','Nicolas Winding Refn',2016),W('black-swan','블랙 스완','Black Swan','film','Darren Aronofsky',2010),W('piano-teacher','피아니스트','La Pianiste','film','Michael Haneke',2001),W('shame','셰임','Shame','film','Steve McQueen',2011),W('different-man','어 디퍼런트 맨','A Different Man','film','Aaron Schimberg',2024),W('saint-maud','세인트 모드','Saint Maud','film','Rose Glass',2019),W('titane','티탄','Titane','film','Julia Ducournau',2021),
W('severance','세브란스: 단절','Severance','series','Dan Erickson',2022,'LONG FORM'),W('mask-girl','마스크걸','Mask Girl','series','Kim Yong-hoon',2023,'EXPLORE'),W('goffman','자아 연출의 사회학','The Presentation of Self in Everyday Life','book','Erving Goffman',1956,'READING'),W('argonauts','아르고호의 선원들','The Argonauts','book','Maggie Nelson',2015,'READING'),W('piano-player-book','피아노 치는 여자','Die Klavierspielerin','book','Elfriede Jelinek',1983,'READING'),W('confessions-mask','가면의 고백','仮面の告白','book','Yukio Mishima',1949,'READING'),
...seedLibrary.map(x=>W(x.id,x.title,x.originalTitle,x.type,x.creator,x.year,'CONNECTED'))
];
const byId=Object.fromEntries(works.map(w=>[w.id,w]));
let state=loadJson(APP_KEY,DEFAULT_STATE);let library=mergeSeed(loadJson(LIB_KEY,seedLibrary));
function loadJson(k,fallback){try{const v=JSON.parse(localStorage.getItem(k));return v?{...fallback,...v}:structuredClone(fallback)}catch{return structuredClone(fallback)}}
function mergeSeed(items){const arr=Array.isArray(items)?items:[];for(const s of seedLibrary){if(!arr.some(x=>x.id===s.id))arr.push({...s});}return arr}
function save(){try{localStorage.setItem(APP_KEY,JSON.stringify(state));localStorage.setItem(LIB_KEY,JSON.stringify(library));}catch(e){toast('브라우저 저장 공간이 부족하거나 차단되어 있습니다. 현재 세션에서는 계속 사용할 수 있어요.')}}
function formatTitle(w){if(!w)return'';return w.type==='book'?`『${w.title}』`:w.type==='article'?`「${w.title}」`:`《${w.title}》`}
function month(){return months[state.selectedMonth]||months['2026-10']}
function compKey(mid,wid){return `${mid}:${wid}`}
function isDone(mid,wid){return !!state.completed[compKey(mid,wid)]}
function toggleDone(mid,wid){const k=compKey(mid,wid);if(state.completed[k])delete state.completed[k];else state.completed[k]=new Date().toISOString();save();render()}
function recordFor(w){const norm=normalize(w.title);return library.find(r=>r.canonicalId===w.id)||library.find(r=>normalize(r.title)===norm && Number(r.year||0)===Number(w.year||0) && r.type===w.type)}
function normalize(s){return String(s||'').toLowerCase().replace(/[《》『』「」<>:：・,.!?'"\-\s]/g,'')}
function statusFor(w,mid){const r=recordFor(w);const inMonth=months[mid]&&(months[mid].core.includes(w.id)||months[mid].supp.includes(w.id));if(r&&inMonth)return 'REVISIT';if(r)return r.historicalStatus==='read'?'ALREADY READ':'ALREADY WATCHED';if(w.role==='CONNECTED')return 'CONNECTED';return 'NEW'}
function progress(mid){const ids=months[mid].core;const d=ids.filter(id=>isDone(mid,id)).length;return {done:d,total:ids.length,pct:Math.round(d/ids.length*100)}}
function setMonth(mid){state.selectedMonth=mid;save();location.hash='#home';render()}
function navTo(route){location.hash=route}
window.addEventListener('hashchange',render);
function route(){return location.hash||'#home'}
