function notesPage(){
  const entries=Object.entries(state.notes).filter(([,v])=>v&&v.trim()).sort((a,b)=>String(state.noteUpdated?.[b[0]]||'').localeCompare(String(state.noteUpdated?.[a[0]]||'')));
  const monthEntries=Object.entries(state.monthNotes).filter(([,v])=>v&&v.trim()).sort((a,b)=>String(state.monthNoteUpdated?.[b[0]]||'').localeCompare(String(state.monthNoteUpdated?.[a[0]]||'')));
  return `${appHeader('#notes')}<main class="shell"><section class="hero"><div class="eyebrow accent-label">NOTES</div><h1>관찰과 연결의 기록</h1><p class="lede">작품을 본 뒤 남긴 문장과 한 달 전체를 돌아보며 남긴 메모를 최근 수정 순으로 모읍니다.</p></section><section class="section notes-list"><div class="section-head"><div><div class="eyebrow accent-label">WORK NOTES</div><h2>작품 메모</h2></div><span class="small muted">${entries.length}</span></div>${entries.length?entries.map(([id,t])=>`<div class="note-item"><div><a href="#work/${id}"><strong>${formatTitle(byId[id]||library.find(r=>r.id===id)||{title:id,type:'film'})}</strong></a>${state.noteUpdated?.[id]?`<div class="small muted">${formatDateKo(state.noteUpdated[id])}</div>`:''}</div><div class="note-preview">${escapeHtml(t).slice(0,240)}</div></div>`).join(''):'<div class="empty">아직 작품 메모가 없습니다.</div>'}</section><section class="section notes-list"><div class="section-head"><div><div class="eyebrow accent-label">MONTH NOTES</div><h2>월별 메모</h2></div><span class="small muted">${monthEntries.length}</span></div>${monthEntries.length?monthEntries.map(([mid,t])=>`<div class="note-item"><div><strong>${months[mid]?.label||mid}</strong>${state.monthNoteUpdated?.[mid]?`<div class="small muted">${formatDateKo(state.monthNoteUpdated[mid])}</div>`:''}</div><div class="note-preview">${escapeHtml(t).slice(0,300)}</div></div>`).join(''):'<div class="empty">아직 월별 메모가 없습니다.</div>'}</section></main>`
}
function mapPage(){
  const m=month(),cfg=siteConfig();
  if(!m.core?.length&&!m.supp?.length)return `${appHeader('#map')}<main class="shell"><section class="empty-instance"><div class="eyebrow accent-label">MAP</div><h1>아직 연결할 프로그램이 없습니다</h1><p class="lede">${escapeHtml(cfg.emptyText||'IMPORT에서 프로그램을 먼저 불러오세요.')}</p><div class="actions"><button class="btn" onclick="navTo('#import')">IMPORT PROGRAM</button></div></section></main>`;
  const ids=[...m.core,...m.supp],p=progress(state.selectedMonth),doneIds=ids.filter(id=>isDone(state.selectedMonth,id));
  const center={x:430,y:270},pos={};
  m.core.forEach((id,i)=>{const a=(Math.PI*2*i/m.core.length)-Math.PI/2;pos[id]={x:center.x+190*Math.cos(a),y:center.y+150*Math.sin(a)}});
  m.supp.forEach((id,i)=>{const a=(Math.PI*2*i/m.supp.length)-Math.PI/2;pos[id]={x:center.x+330*Math.cos(a),y:center.y+225*Math.sin(a)}});
  const seen=new Set(),edges=[];
  for(const id of ids){for(const t of connectionIds(id)){if(!ids.includes(t))continue;const k=[id,t].sort().join('|');if(!seen.has(k)){seen.add(k);edges.push([id,t])}}}
  const unlocked=unlockedConcepts(state.selectedMonth);
  return `${appHeader('#map')}<main class="shell">
    <section class="hero program-hero"><div class="eyebrow accent-label">MAP · ${m.label}</div><h1>관계의 지도</h1><p class="lede">처음에는 이름 없는 점만 남아 있습니다. 작품을 완료할수록 제목과 연결선이 드러나며 한 달의 지도가 별자리처럼 완성됩니다.</p>${monthSwitcher()}${progressHtml(state.selectedMonth)}</section>
    <section class="section">
      <div class="map-status"><div><span class="eyebrow accent-label">CONSTELLATION</span><strong>${doneIds.length} / ${ids.length} nodes revealed</strong></div><div class="map-concepts">${unlocked.map(c=>`<span>◆ ${escapeHtml(c)}</span>`).join('')}</div></div>
      <div class="mapbox constellation"><div class="map-inner"><svg class="map-lines">${edges.map(([a,b])=>{const on=isDone(state.selectedMonth,a)&&isDone(state.selectedMonth,b);return `<line class="${on?'active-line':'locked-line'}" x1="${pos[a].x}" y1="${pos[a].y}" x2="${pos[b].x}" y2="${pos[b].y}"/>`}).join('')}</svg>
      ${ids.map(id=>{const w=byId[id],pt=pos[id],done=isDone(state.selectedMonth,id),core=m.core.includes(id);return `<button class="star-node ${core?'core':'supplementary'} ${done?'revealed':'locked'}" style="left:${pt.x}px;top:${pt.y}px" ${done?`onclick="navTo('#work/${id}')"`:'disabled'} aria-label="${escapeAttr(w.title)} ${done?'활성':'잠김'}"><i></i><span>${done?escapeHtml(w.title):''}</span></button>`}).join('')}
      <div class="constellation-center" style="left:${center.x}px;top:${center.y}px"><span>${p.done?escapeHtml(m.ko):'· · ·'}</span></div></div></div>
      <div class="map-legend"><span><i class="legend-dot done-dot"></i>완료하면 제목 공개</span><span>● CORE</span><span>◆ SUPPLEMENTARY</span></div>
    </section>
  </main>`
}
function archivePage(){
  return `${appHeader('#archive')}<main class="shell"><section class="hero"><div class="eyebrow accent-label">ARCHIVE</div><h1>완성된 챕터</h1><p class="lede">한 달이 끝나면 감상한 영화, 선택한 가지, 열린 개념과 메모가 하나의 챕터로 남습니다.</p></section><section class="archive-chapters">${Object.entries(months).map(([mid,m],idx)=>{const p=progress(mid),doneCore=m.core.filter(id=>isDone(mid,id)),branches=m.supp.filter(id=>isAdded(mid,id)),concepts=unlockedConcepts(mid),complete=p.done===p.total;return `<article class="archive-chapter ${complete?'complete':''}"><header><div class="chapter-number">CHAPTER ${String(idx+1).padStart(2,'0')}</div><div class="eyebrow ${complete?'accent-label':''}">${m.label}</div><h2>${m.title}</h2><p>${m.ko}</p><div class="chapter-progress"><strong>${p.done}/${p.total}</strong><span>${complete?'CHAPTER COMPLETE':'IN PROGRESS'}</span></div></header><div class="chapter-body"><section><div class="eyebrow accent-label">WATCHED</div><ol class="archive-work-list">${doneCore.length?doneCore.map(id=>`<li><a href="#work/${id}">${formatTitle(byId[id])}</a><span>${formatDateKo(completionDate(mid,id))}</span></li>`).join(''):'<li class="muted">아직 완료한 핵심 작품이 없습니다.</li>'}</ol></section><section><div class="eyebrow accent-label">MY BRANCHES</div><div class="chapter-branches">${branches.length?branches.map(id=>`<a href="#work/${id}">${formatTitle(byId[id])}</a>`).join(''):'<span class="muted">선택한 보조 텍스트가 없습니다.</span>'}</div></section><section><div class="eyebrow accent-label">UNLOCKED CONCEPTS</div><div class="concept-list">${concepts.length?concepts.map(c=>`<span>◆ ${escapeHtml(c)}</span>`).join(''):'<span class="muted">아직 열린 개념이 없습니다.</span>'}</div></section><section class="chapter-note"><div class="eyebrow accent-label">MONTH NOTE</div><p>${escapeHtml(state.monthNotes[mid]||'아직 월별 메모가 없습니다.')}</p></section></div></article>`}).join('')}</section></main>`
}
function importPage(){
  return `${appHeader('#import')}<main class="shell">
    <section class="hero"><div class="eyebrow accent-label">IMPORT / BACKUP</div><h1>새 커리큘럼과 기존 기록 가져오기</h1><p class="lede">ChatGPT와 새 프로그램을 완성한 뒤 <strong>CINEMATHEQUE IMPORT PACKAGE v2</strong>를 받아 아래에 붙여넣으면 새 달을 계속 추가할 수 있습니다. 가져오기 전에는 기존 작품 재사용·신규 작품·업데이트 범위를 먼저 확인합니다.</p></section>

    <section class="section curriculum-import-section">
      <div class="section-head"><div><div class="eyebrow accent-label">CINEMATHEQUE IMPORT PACKAGE · V2</div><h2>월별 커리큘럼 추가</h2></div></div>
      <div class="import-package-grid">
        <div>
          <textarea id="cinema-package" class="package-textarea" spellcheck="false" placeholder='ChatGPT에서 받은 JSON 패키지를 여기에 붙여넣으세요.&#10;&#10;예: {"schema":"woodsy-cinematheque-import-v2","month":{...},"works":[...]}'></textarea>
          <div class="actions"><button id="cinema-package-preview" class="btn secondary">미리보기</button><button id="cinema-package-import" class="btn">커리큘럼 반영</button></div>
        </div>
        <aside>
          <div id="cinema-package-result" class="import-preview package-preview">아직 패키지를 입력하지 않았습니다.</div>
          <details class="package-help"><summary>패키지에 포함되는 정보</summary><p>월 제목·소제목·프로그램 노트·CORE·보조 텍스트·THIS WEEK'S TEXT·개념·작품 기본정보·VIEWING POINTS·KEYWORDS·인용/큐레이터 노트·REFERENCES·CONNECTIONS·WHERE TO WATCH·스틸/책 표지와 focal point까지 한 번에 가져올 수 있습니다.</p><p>기존 작품 ID가 포함되면 중복 생성하지 않고 해당 작품을 재사용합니다.</p></details>
        </aside>
      </div>
    </section>

    <section class="section"><div class="grid two">
      <div class="filebox"><div class="eyebrow accent-label">BOOKS · NOTION</div><h3>독서 기록 가져오기</h3><input type="file" id="books-file" accept="application/json,.json"><div class="actions"><button class="btn" onclick="importBooksJson(document.getElementById('books-file').files[0])">Books JSON 가져오기</button></div><p class="small muted" style="margin-top:16px">기존 영화 기록은 변경하지 않고 Books 전용 저장소에 병합합니다.</p></div>
      <div class="filebox"><div class="eyebrow accent-label">WATCHAPEDIA CSV</div><h3>감상 기록 가져오기</h3><input type="file" id="watcha-file" accept=".csv,text/csv"><div id="watcha-preview" class="import-preview">파일을 선택하면 미리보기가 표시됩니다.</div><div class="actions"><button class="btn" onclick="importWatcha()">확인 후 가져오기</button></div></div></section>

    <section class="section"><div class="grid two">
      <div class="filebox"><div class="eyebrow accent-label">BACKUP</div><h3>JSON 내보내기 / 복원</h3><div class="actions"><button class="btn secondary" onclick="exportBackup()">JSON 내보내기</button><label class="btn secondary">JSON 복원<input type="file" id="restore-file" accept="application/json,.json" style="display:none" onchange="restoreBackup(this.files[0])"></label></div><p class="small muted" style="margin-top:16px">커리큘럼 Import로 추가한 달도 백업 파일에 함께 저장됩니다.</p></div>
    </div></section>

    <section class="section"><div class="grid two">
      <div class="filebox"><div class="eyebrow accent-label">ADD A BOOK</div><h3>책 단일 추가</h3><input class="search" id="book-title" placeholder="제목"><input class="search" id="book-author" placeholder="저자"><input class="search" id="book-year" placeholder="연도" inputmode="numeric"><div class="actions"><button class="btn" onclick="addBook()">READ로 추가</button></div></div>
      <div><div class="eyebrow accent-label">IMPORT RESULT</div><div id="import-result" class="notice">아직 가져온 파일이 없습니다.</div><div class="actions"><button class="btn secondary" onclick="resetAll()">모든 로컬 기록 초기화</button></div></div>
    </div></section>
  </main>`
}
function adminPage(){
  if(!isAdminUnlocked()){
    return `${appHeader('#admin')}<main class="shell"><section class="hero"><div class="eyebrow accent-label">ADMIN MODE</div><h1>개인 아카이브 로그인</h1><p class="lede">Supabase 계정으로 로그인하면 리뷰·별점·비공개 메모와 커리큘럼 편집 기능이 열립니다.</p></section><section class="section">${archiveLoginPanel()}</section></main>`;
  }
  if(!Object.keys(months).length)return `${appHeader('#admin')}<main class="shell"><section class="empty-instance"><div class="eyebrow accent-label">ADMIN MODE</div><h1>먼저 프로그램을 불러오세요</h1><p class="lede">빈 영화모임 페이지에서는 IMPORT로 첫 커리큘럼을 추가한 뒤 편집 기능을 사용할 수 있습니다.</p><div class="actions"><button class="btn" onclick="navTo('#import')">IMPORT PROGRAM</button></div></section></main>`;
  const mid=window._adminMonth||state.selectedMonth,m=months[mid]||month(),wid=window._adminWork||m.core[0],w=byId[wid]||works[0],st=stills[wid]||{},ed=editorialFor(wid)||{};
  const q=ed.quote||{};
  return `${appHeader('#admin')}<main class="shell">
    <section class="hero"><div class="eyebrow accent-label">ADMIN MODE</div><h1>개인 시네마테크 편집실</h1><p class="lede">월별 프로그램과 작품 큐레이션을 코드 없이 수정합니다. 변경 내용은 현재 브라우저와 JSON 백업에 저장됩니다.</p><div class="actions"><button class="btn secondary" onclick="adminLogout()">관리자 모드 잠그기</button></div></section>
    <section class="section"><div class="admin-panel"><div class="eyebrow accent-label">AUTO POSTER ARCHIVE · ACTIVE</div><h2>포스터 자동 아카이빙</h2><p class="lede">확인 가능한 포스터를 서버에서 자동으로 탐색해 Supabase Storage에 보관합니다. 수동 작업이 필요한 작품은 각 영화 상세의 EDIT에서 직접 업로드하거나 URL을 가져올 수 있습니다.</p></div></section>
    <section class="section"><div class="admin-panel"><div class="eyebrow accent-label">MONTH PROGRAM</div><h2>월별 편집</h2><select id="admin-month-select" class="select">${Object.entries(months).map(([id,x])=>`<option value="${id}" ${id===mid?'selected':''}>${x.label}</option>`).join('')}</select><div class="admin-grid"><label class="admin-label">영문 제목<input id="admin-month-title" class="search" value="${escapeAttr(m.title)}"></label><label class="admin-label">제목 줄바꿈 · | 구분<input id="admin-month-lines" class="search" value="${escapeAttr((m.titleLines||[m.title]).join(' | '))}"></label><label class="admin-label">한국어 소제목<input id="admin-month-ko" class="search" value="${escapeAttr(m.ko)}"></label><label class="admin-label">THIS WEEK'S TEXT<select id="admin-month-feature" class="select">${m.core.map(id=>`<option value="${id}" ${id===m.featureId?'selected':''}>${escapeHtml(byId[id].title)}</option>`).join('')}</select></label></div><label class="admin-label">프로그램 노트<textarea id="admin-month-note">${escapeHtml(m.note)}</textarea></label><label class="admin-label">월 개념 · 쉼표로 구분<input id="admin-month-concepts" class="search" value="${escapeAttr(m.concepts.join(', '))}"></label><div class="actions"><button class="btn" onclick="saveAdminMonth()">월 프로그램 저장</button></div></div></section>
    <section class="section"><div class="admin-panel"><div class="eyebrow accent-label">WORK EDITOR</div><h2>작품 큐레이션</h2><select id="admin-work-select" class="select">${works.map(x=>{const label=x.type==='book'?`『${escapeHtml(x.title)}』`:`&lt;${escapeHtml(x.title)}&gt;`;return `<option value="${x.id}" ${x.id===wid?'selected':''}>${label} · ${x.year}</option>`}).join('')}</select>
      <div class="admin-grid"><label class="admin-label">표시 제목<input id="admin-work-title" class="search" value="${escapeAttr(w.title)}"></label><label class="admin-label">원제<input id="admin-work-original" class="search" value="${escapeAttr(w.originalTitle||'')}"></label><label class="admin-label">감독 / 저자<input id="admin-work-creator" class="search" value="${escapeAttr(w.creator||'')}"></label><label class="admin-label">연도<input id="admin-work-year" class="search" value="${w.year||''}"></label><label class="admin-label">역할<select id="admin-work-role" class="select">${['CORE','LONG FORM','READING','EXPLORE','CONNECTED'].map(x=>`<option ${x===w.role?'selected':''}>${x}</option>`).join('')}</select></label><label class="admin-label">WHERE TO WATCH<input id="admin-work-service" class="search" value="${escapeAttr(serviceFor(wid))}"></label><label class="admin-label">확인 시점<input id="admin-work-checked" class="search" value="${escapeAttr(ed.checked||'')}"></label></div>
      <label class="admin-label">LOGLINE<textarea id="admin-work-logline">${escapeHtml(ed.logline||'')}</textarea></label>
      <div class="admin-grid"><label class="admin-label">VIEWING POINTS · 한 줄에 하나<textarea id="admin-work-points">${escapeHtml((ed.viewingPoints||[]).join('\n'))}</textarea></label><label class="admin-label">REFERENCES · 한 줄에 하나<textarea id="admin-work-references">${escapeHtml((ed.references||[]).join('\n'))}</textarea></label></div>
      <div class="admin-grid"><label class="admin-label">KEYWORDS · 쉼표<input id="admin-work-keywords" class="search" value="${escapeAttr((ed.keywords||[]).join(', '))}"></label><label class="admin-label">CONNECTIONS · 작품 ID 쉼표<input id="admin-work-connections" class="search" value="${escapeAttr((connectionIds(wid)||[]).join(', '))}"></label><label class="admin-label">UNLOCK CONCEPTS · 쉼표<input id="admin-work-concepts" class="search" value="${escapeAttr((conceptIds(wid)||[]).join(', '))}"></label></div>
      <div class="admin-subsection"><div class="eyebrow accent-label">QUOTE / CURATOR'S NOTE</div><div class="admin-grid"><label class="admin-label">종류<select id="admin-quote-kind" class="select"><option value="direct" ${q.kind!=='curator'?'selected':''}>DIRECT QUOTE</option><option value="curator" ${q.kind==='curator'?'selected':''}>CURATOR'S NOTE</option></select></label><label class="admin-label">출처<input id="admin-quote-source" class="search" value="${escapeAttr(q.source||'')}"></label></div><label class="admin-label">한국어<input id="admin-quote-text" class="search" value="${escapeAttr(q.text||'')}"></label><label class="admin-label">원어<input id="admin-quote-original" class="search" value="${escapeAttr(q.original||'')}"></label><label class="admin-label">영어<input id="admin-quote-en" class="search" value="${escapeAttr(q.en||'')}"></label></div>
      <div class="admin-subsection"><div class="eyebrow accent-label">VISUAL</div><div class="admin-grid"><label class="admin-label">비주얼 타입<select id="admin-visual-type" class="select"><option value="still" ${(st.visualType||visualFor(wid).type||'still')==='still'?'selected':''}>STILL · 16:9</option><option value="cover" ${(st.visualType||visualFor(wid).type)==='cover'?'selected':''}>COVER · 책 표지</option><option value="typographic" ${(st.visualType||visualFor(wid).type)==='typographic'?'selected':''}>TYPOGRAPHIC</option></select></label><label class="admin-label">이미지 URL<input id="admin-still-url" class="search" value="${escapeAttr(st.url||visualFor(wid).url||'')}"></label><label class="admin-label">출처<input id="admin-still-source" class="search" value="${escapeAttr(st.source||visualFor(wid).source||'')}"></label><label class="admin-label">FOCAL POSITION<input id="admin-still-position" class="search" value="${escapeAttr(focalFor(wid))}" placeholder="50% 50%"></label></div><div class="admin-preview">${w.type==='film'?visualHtml(w):supplementaryVisualHtml(w)}</div></div>
      <div class="actions"><button class="btn" onclick="saveAdminWork()">작품 큐레이션 저장</button></div>
    </div></section>
    <section class="section"><div class="eyebrow accent-label">RESET OVERRIDES</div><h2>관리자 수정만 초기화</h2><p class="program-note">감상 완료·메모·MASTER LIBRARY는 유지합니다.</p><button class="btn secondary" onclick="resetAdminOverrides()">관리자 수정 초기화</button></section>
  </main>`
}
function notFound(){return `${appHeader('')}<main class="shell"><section class="hero"><div class="eyebrow">404</div><h1>상영 예정이 없습니다</h1><button class="btn" onclick="navTo('#home')">홈으로</button></section></main>`}
function render(){const r=route();let html;if(r==='#home')html=home();else if(r==='#curriculum')html=curriculum();else if(r==='#library')html=libraryPage();else if(r==='#books')html=booksPage();else if(r==='#notes')html=notesPage();else if(r==='#map')html=mapPage();else if(r==='#archive')html=archivePage();else if(r==='#import')html=importPage();else if(r==='#admin')html=adminPage();else if(r.startsWith('#work/'))html=workPage(r.split('/')[1]);else if(r.startsWith('#book/'))html=bookPage(r.split('/')[1]);else html=notFound();document.getElementById('app').innerHTML=html}
